steps:
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'test'
  args: ['presubmit']
  waitFor: ['yarn']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1']
  secretEnv: ['BROWSERSTACK_KEY']
- name: 'python:3.6'
  entrypoint: 'bash'
  args: ['./run_python_tests.sh']
  waitFor: ['-']
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
